package responses;

public interface Responses {
    String MAIN_MENU = "1 -> Sign up\n2 -> Sign in\n0 -> Exit";
    String USER_ALREADY_EXIST = "USER_ALREADY_EXIST";
    String SUCCESS = "SUCCESSFULLY_COMPLETED";
    String USER_NOT_FOUND = "USER_NOT_FOUND";
    String PRODUCT_NOT_FOUND = "USER_NOT_FOUND";
    String CATEGORY_ALREADY_EXISTS = "CATEGORY_ALREADY_EXISTS";
    String SOMETHING_WENT_WRONG = "SOMETHING_WENT_WRONG";
    String CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND";
}
